# -*- coding: utf-8 -*-
"""Web Scrapping Goal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12CpBcavaiJYauw5IrnwsMnfSqcX_U3Rm
"""

import requests
from bs4 import BeautifulSoup as bs
import pandas as pd
from prettytable import PrettyTable
from fpdf import FPDF
import pandas as pd

url = requests.get('https://www.goal.com/id/berita/jadwal-siaran-langsung-sepakbola/1qomojcjyge9n1nr2voxutdc1n').text

url_soup = bs(url, 'lxml')
judul = url_soup.find_all('h2')
tanggal_raw = url_soup.find_all('h3')
div_table = url_soup.find_all('div', {"class":"table-container-scroll"})

table = []
tanggal = []

for x in div_table:
  table.append(x)

for x in tanggal_raw:
  tanggal.append(x)

df_list = []

for jadwal in range(0, len(div_table)):
    kick_off = []
    pertandingan = []
    kompetisi = []
    stasiun_tv = []

    for row in table[jadwal].find_all('tr'):
        tds = row.find_all('td')
        if tds:
            kick_off.append(tds[0].text)
            pertandingan.append(tds[1].text)
            kompetisi.append(tds[2].text)
            stasiun_tv.append(tds[3].text)

    data = {
        'Kick-off': kick_off,
        'Pertandingan': pertandingan,
        'Kompetisi': kompetisi,
        'Stasiun TV': stasiun_tv
    }

    df_list.append(pd.DataFrame(data))

# print(df_list[0])

for i in range(0, len(df_list)):
  tgl = tanggal[i].text
  table = PrettyTable(["Kick-off", "Pertandingan", "Kompetisi", "Stasiun TV"])
  for k, p, kom, s in df_list[i].values:
      table.add_row([k, p, kom, s])
  print(tgl)
  print(table)

for df in df_list:
    print("Mencetak DataFrame ke PDF:")
    print(df)

def df_to_pdf(df_list, file_name):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=10)
    index = 0

    for df in df_list:
        if df.empty:
            print("DataFrame kosong, tidak ada data untuk ditampilkan.")
            continue

        pdf.set_font("Arial", 'B', size=10)
        tgl = tanggal[index].text
        pdf.cell(0, 10, tgl, 1, 1, 'C')
        index += 1

        # Headers
        pdf.set_font("Arial", 'B', size=10)
        col_widths = [40, 80, 30, 40]

        headers = df.columns.tolist()
        for idx, header in enumerate(headers):
            pdf.cell(col_widths[idx], 10, header, border=1)
        pdf.ln()

        # Data
        pdf.set_font("Arial", size=10)
        for i, row in df.iterrows():
            for col_idx, data in enumerate(row):
              pdf.cell(col_widths[col_idx], 10, str(data), border=1)
            pdf.ln()

        pdf.ln(10)

    pdf.output(file_name)

df_to_pdf(df_list, "jadwal_pertandingan.pdf")

import datetime

x = datetime.datetime.now()
day = x.strftime("%d")
print(day)

for i in tanggal:
  tanggal_saja = i.text.split(' ')[1]
  print(tanggal_saja)